language: cpp
compiler: clang++
os: osx
osx_image: xcode10.2
addons:
  homebrew:
    update: true
    brewfile: true
before_install:
#- brew cask uninstall oclint # still necessary for xcode9.3, xcode9.4 images https://github.com/travis-ci/travis-ci/issues/8826
script:
- sh ./scripts/build_osx.sh
#before_deploy:
#- cd $TRAVIS_BUILD_DIR/bin/release5
#- "$(brew --prefix qt)/bin/macdeployqt Z3DScanner.app -libpath=. -qmldir=../../Z3DScanner/qml"
#- "$(brew --prefix qt)/bin/macdeployqt Z3DCloudViewer.app -libpath=. -qmldir=../../Z3DCloudViewer/qml"
#- "$(brew --prefix qt)/bin/macdeployqt Z3DCameraViewer.app -libpath=."
#- "$(brew --prefix qt)/bin/macdeployqt Z3DCameraCalibration.app -libpath=."
#- "$(brew --prefix qt)/bin/macdeployqt Z3DMultiCameraCalibration.app -libpath=."
#deploy:
#  provider: releases
#  api_key:
#    secure: "18Pmq79NxWaZlwcI4SBJAAXdkhp6sb4h5GSlUhtxhx5D/FCiyYYfKYBBYM/F5O/hklrIOVuGz8TzQ2iKgRxUPlXli804EO0CWWT/FpsniBVhoRNme47EsXpD+pPeQ9YlGwW5bAWUiB9gIxYzLOo/jx/6kEjNujY+CLbfqh5YOs/tpH+dDdGRSR/tAGM5uxPlf16kxgFOeiKlhFTRR5ESGMsL/zo//stoa1Yc1GdlVtguSoyiuSyyWd3zqQrpsCWorusDH6wGyKRiatMhCnKFYDuE4jguSTO0+659YT1ZbiNWQ1IQxFRfDslzVh1FjtZ7CjvNk7nGH747wdW7EOOzJjPhdSh0KU5qWkSk6dNC9f0hikriHrLAePAjL1fGRaF9K5l4xf7cWpoN2oWclra5RlbAJ0Pe7zmQInqdCHho2uxgNmpouqefm0sBlOIheIxNTdIClcOTr4eYfplj58LXV61CZE0TAS1hn0ImrisaPmcejj7vyJp0EhFQ9PMZTIgDEvQv/MFB65a0quNW7chL6/EnvZ8WkeVB1mj7MKK4I7WSpNhb+A6kI/o3MkEPTM6k0gFNYoMIWY9FG80S+0XcMM+xMBsdUNNlGoTNcgC2DOZdr/Tmjf8NeOC9rnfCV/Q7InVvbP7KTe9AMq2nlse9y8hXR+BuU1+7wjnZI7hzPMA="
#  file_glob: true
#  file: $TRAVIS_BUILD_DIR/bin/release5/*.app
#  skip_cleanup: true
#  on:
#    repo: nikolaseu/neuvision
#    #all_branches: true
#    tags: true
#  draft: true
#  prerelease: true
