image: Visual Studio 2017
platform: x64
configuration: Release
init:
  # To get RDP details for the current build worker
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
on_finish:
  # If you need to investigate worker on build finish add $blockRdp = $true; to display Remote Desktop connection details and pause the build until a special “lock” file on VM desktop is deleted:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
environment:
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
cache:
  - C:\Tools\vcpkg\installed\
install: # scripts that run after cloning repository
  # Update appveyor build version using git repository tags
  - cmd: |
      for /f %%a in ('"git describe --always --tags --broken --long"') do set gitVersion=%%a
      appveyor UpdateBuild -Version "%gitVersion%-build-%APPVEYOR_BUILD_NUMBER%"
  # Download plugin deps: Basler pylon, AVT vimba, etc
  - appveyor DownloadFile "%THIRDPARTY_LIBS_ZIP%" -FileName 3rdpartylibs.zip
  - dir
  - md 3rdpartylibs
  - cd 3rdpartylibs
  - pwd
  - dir
  - 7z x ..\3rdpartylibs.zip > nul
  - dir
  - set AVT_VIMBA_DIR=C:\projects\neuvision\3rdpartylibs\avtvimba
  - set PYLON_DEV_DIR=C:\projects\neuvision\3rdpartylibs\pylon
  - cd ..
  - pwd
  - dir
  # Download/install deps
  # we update vcpkg/installed folder manually since it takes too long
  # next runs should use appveyor cache and work ... we need to automate this!
  - vcpkg list
  # pause the build until a special “lock” file on VM desktop is deleted
  # useful to manually copy/download/update vcpkg libs like vtk & pcl that cannot be built in CI
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - vcpkg install opencv:x64-windows --recurse
  #- vcpkg install vtk:x64-windows # takes a really long time, build won't work on CI
  #- vcpkg install pcl:x64-windows # takes a really long time, build won't work on CI
  # Just to debug what vcpkg installed
  #- dir "C:/Tools/vcpkg/installed/x64-windows" & exit 0
  #- dir "C:/Tools/vcpkg/installed/x64-windows/include" & exit 0
  - dir "C:/Tools/vcpkg/installed/x64-windows/lib" & exit 0
  - dir "C:/Tools/vcpkg/installed/x64-windows/bin" & exit 0
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
  - call .\scripts\build_win.bat
after_build:
  - cd %APPVEYOR_BUILD_FOLDER%/build/bin
  - call "C:\Qt\5.12\msvc2017_64\bin\windeployqt.exe" -concurrent -multimedia -multimediawidgets --qmldir ./../../apps/Z3DScanner/qml/ --qmldir ./../../apps/Z3DCloudViewer/qml/ ./Z3DScanner.exe ./Z3DCloudViewer.exe
  - cp "C:/Tools/vcpkg/installed/x64-windows/bin"/*.dll . # copy dependencies
  - del /s /q *.lib # remove unnecessary lib files
  - del /s /q *.exp # remove unnecessary exp files
artifacts:
  # pushing entire folder as a zip archive
  - path: build/bin
    name: NEUVision-Windows-x64-v$(appveyor_build_version)
deploy:
  release: NEUVision-Windows-x64-v$(appveyor_build_version)
  description: 'Automatic snapshot release from CI'
  provider: GitHub
  auth_token:
    secure: aHV+YRaW2BChwsCNWDuyIcIMS6WLL8Y/owvslumt0sXRrtbtPHHj3p7/7OdToJ5t
  artifact: /.*\.zip/            # upload all zip packages to release assets
  draft: true
  prerelease: true
  on:
#    branch: master               # release from master branch only
    appveyor_repo_tag: true      # deploy on tag push only
